CREATE TABLE customerLg(
CUSTOMERS_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
LAST_NAME VARCHAR (50) NOT NULL,
FIRST_NAME VARCHAR (50) NOT NULL,
PHONE NCHAR(13),
CUS_ADDRESS NVARCHAR (255),
CITY NVARCHAR(50),
CUS_STATE VARCHAR(15),
ZIP NCHAR(8)
);

CREATE TABLE INVOICE(
INVOICE_ID INT IDENTITY (20,1) NOT NULL PRIMARY KEY,
CUSTOMERS_ID INT NOT NULL,
INVOICE_DATE DATETIME NOT NULL,
CONSTRAINT FK_CUS_CUSTOMERID
FOREIGN KEY(CUSTOMERS_ID)
 REFERENCES customerlg
 );

GO

----INSERT VALUES------
 SET IDENTITY_INSERT customerLg ON;

 INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(2,'Cinda','WHITMER',8657243,' 5 LAKE HOUSE','AIBER','LON', 'L12RT');

SET IDENTITY_INSERT customerLg OFF;


SET IDENTITY_INSERT customerLg ON;

 INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(3,'Sopoline','Weber',0123454,' 5 High Harbour','Raton','NAFL', 'Q12UIT');

INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(4,'Neil','Scot',0120984,' 7 Shady lane','lake city','Fort Meyer', 'N23610');

INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(5,'Anthony','Rick',0134567,' 91 Downlane','AbbeyFort','London', 'T33KNO');

INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(6,'Yamine','Adam',0156490,'67 indiancrest','DAYON','Oakland', 'R18UIT');

INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(7,'Helen','Mayor',0154781,' 9 crawl Road','Nortvil','POINTES', 'H3467');

INSERT into dbo.customerLg(CUSTOMERS_ID,LAST_NAME,FIRST_NAME,PHONE,CUS_ADDRESS,CITY,CUS_STATE,ZIP)
VALUES(8,'Clare','Morrison',0179350,' 23 Highlane','uveliw','Mexscot', 'Ge4578');

SET IDENTITY_INSERT customerLg OFF;
SET IDENTITY_INSERT dbo.INVOICE ON;
 INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID,INVOICE_DATE)
VALUES(21, 2,CAST(N'2015 -01-01 00:00:00.000' AS datetime));

INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID,INVOICE_DATE)
VALUES(22, 3,CAST(N'2015 -01-02 00:00:00.000' AS datetime));

INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID, INVOICE_DATE)
VALUES(23, 4,CAST(N'2015 -01-07 00:00:00.000' AS datetime));

INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID,INVOICE_DATE)
VALUES(24, 5,CAST(N'2015 -01-21 00:00:00.000' AS datetime));

INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID,INVOICE_DATE)
VALUES(25, 6,CAST(N'2015 -01-23 00:00:00.000' AS datetime));

INSERT into dbo.INVOICE(INVOICE_ID,CUSTOMERS_ID,INVOICE_DATE)
VALUES(26, 7,CAST(N'2015 -01-15 00:00:00.000' AS datetime));
SET IDENTITY_INSERT dbo.INVOICE OFF;